project_id = "zmeurkidfsmkedyampoy"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.send-booking-confirmation]
verify_jwt = false

[functions.fetch-available-requests]
verify_jwt = true

[functions.create-booking-payment]
verify_jwt = true

[functions.select-sitter]
verify_jwt = true

[functions.verify-booking-payment]
verify_jwt = false

[functions.respond-to-booking]
verify_jwt = true

[functions.notify-available-sitters]
verify_jwt = true

[functions.send-booking-notification]
verify_jwt = false

[functions.send-parent-notification]
verify_jwt = false

[functions.send-sitter-confirmation]
verify_jwt = false