// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmeurkidfsmkedyampoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InptZXVya2lkZnNta2VkeWFtcG95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDIyODEsImV4cCI6MjA3MTg3ODI4MX0.-NdrdTXyXnwBpNtTf6jf3HCuMfrkI9DCNMAZ5xO4J8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});